//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoronaDataCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Fault_Data_old
    {
        public int id { get; set; }
        public string EqID { get; set; }
        public string FauCodeA { get; set; }
        public string FauCodeB { get; set; }
        public Nullable<System.DateTime> FauTime { get; set; }
        public Nullable<int> parm_001 { get; set; }
        public Nullable<int> parm_002 { get; set; }
        public Nullable<int> parm_003 { get; set; }
        public Nullable<int> parm_004 { get; set; }
        public Nullable<int> parm_005 { get; set; }
        public Nullable<int> parm_006 { get; set; }
        public Nullable<int> parm_007 { get; set; }
        public Nullable<int> parm_008 { get; set; }
        public Nullable<int> parm_009 { get; set; }
        public Nullable<int> parm_010 { get; set; }
        public Nullable<int> parm_011 { get; set; }
        public Nullable<int> parm_012 { get; set; }
        public Nullable<int> parm_013 { get; set; }
        public Nullable<int> parm_014 { get; set; }
        public Nullable<int> parm_015 { get; set; }
        public Nullable<int> parm_016 { get; set; }
        public Nullable<int> parm_017 { get; set; }
        public Nullable<int> parm_018 { get; set; }
        public Nullable<int> parm_019 { get; set; }
        public Nullable<int> parm_020 { get; set; }
        public Nullable<int> parm_021 { get; set; }
        public Nullable<int> parm_022 { get; set; }
        public Nullable<int> parm_023 { get; set; }
        public Nullable<int> parm_024 { get; set; }
        public Nullable<int> parm_025 { get; set; }
        public Nullable<int> parm_026 { get; set; }
        public Nullable<int> parm_027 { get; set; }
        public Nullable<int> parm_028 { get; set; }
        public Nullable<int> parm_029 { get; set; }
        public Nullable<int> parm_030 { get; set; }
        public Nullable<int> parm_031 { get; set; }
        public Nullable<int> parm_032 { get; set; }
        public Nullable<int> parm_033 { get; set; }
        public Nullable<int> parm_034 { get; set; }
        public Nullable<int> parm_035 { get; set; }
        public Nullable<int> parm_036 { get; set; }
        public Nullable<int> parm_037 { get; set; }
        public Nullable<int> parm_038 { get; set; }
        public Nullable<int> parm_039 { get; set; }
        public Nullable<int> parm_040 { get; set; }
        public Nullable<int> parm_041 { get; set; }
        public Nullable<int> parm_042 { get; set; }
        public Nullable<int> parm_043 { get; set; }
        public Nullable<int> parm_044 { get; set; }
        public Nullable<int> parm_045 { get; set; }
        public Nullable<int> parm_046 { get; set; }
        public Nullable<int> parm_047 { get; set; }
        public Nullable<int> parm_048 { get; set; }
        public Nullable<int> parm_049 { get; set; }
        public Nullable<int> parm_050 { get; set; }
        public Nullable<int> parm_051 { get; set; }
        public Nullable<int> parm_052 { get; set; }
        public Nullable<int> parm_053 { get; set; }
        public Nullable<int> parm_054 { get; set; }
        public Nullable<int> parm_055 { get; set; }
        public Nullable<int> parm_056 { get; set; }
        public Nullable<int> parm_057 { get; set; }
        public Nullable<int> parm_058 { get; set; }
        public Nullable<int> parm_059 { get; set; }
        public Nullable<int> parm_060 { get; set; }
        public Nullable<int> parm_061 { get; set; }
        public Nullable<int> parm_062 { get; set; }
        public Nullable<int> parm_063 { get; set; }
        public Nullable<int> parm_064 { get; set; }
        public Nullable<int> parm_065 { get; set; }
        public Nullable<int> parm_066 { get; set; }
        public Nullable<int> parm_067 { get; set; }
        public Nullable<int> parm_068 { get; set; }
        public Nullable<int> parm_069 { get; set; }
        public Nullable<int> parm_070 { get; set; }
        public Nullable<int> parm_071 { get; set; }
        public Nullable<int> parm_072 { get; set; }
        public Nullable<int> parm_073 { get; set; }
        public Nullable<int> parm_074 { get; set; }
        public Nullable<int> parm_075 { get; set; }
        public Nullable<int> parm_076 { get; set; }
        public Nullable<int> parm_077 { get; set; }
        public Nullable<int> parm_078 { get; set; }
        public Nullable<int> parm_079 { get; set; }
        public Nullable<int> parm_080 { get; set; }
        public Nullable<int> parm_081 { get; set; }
        public Nullable<int> parm_082 { get; set; }
        public Nullable<int> parm_083 { get; set; }
        public Nullable<int> parm_084 { get; set; }
        public Nullable<int> parm_085 { get; set; }
        public Nullable<int> parm_086 { get; set; }
        public Nullable<int> parm_087 { get; set; }
        public Nullable<int> parm_088 { get; set; }
        public Nullable<int> parm_089 { get; set; }
        public Nullable<int> parm_090 { get; set; }
        public Nullable<int> parm_091 { get; set; }
        public Nullable<int> parm_092 { get; set; }
        public Nullable<int> parm_093 { get; set; }
        public Nullable<int> parm_094 { get; set; }
        public Nullable<int> parm_095 { get; set; }
        public Nullable<int> parm_096 { get; set; }
        public Nullable<int> parm_097 { get; set; }
        public Nullable<int> parm_098 { get; set; }
        public Nullable<int> parm_099 { get; set; }
        public Nullable<int> parm_100 { get; set; }
        public Nullable<int> parm_101 { get; set; }
        public Nullable<int> parm_102 { get; set; }
        public Nullable<int> parm_103 { get; set; }
        public Nullable<int> parm_104 { get; set; }
        public Nullable<int> parm_105 { get; set; }
        public Nullable<int> parm_106 { get; set; }
        public Nullable<int> parm_107 { get; set; }
        public Nullable<int> parm_108 { get; set; }
        public Nullable<int> parm_109 { get; set; }
        public Nullable<int> parm_110 { get; set; }
        public Nullable<int> parm_111 { get; set; }
        public Nullable<int> parm_112 { get; set; }
        public Nullable<int> parm_113 { get; set; }
        public Nullable<int> parm_114 { get; set; }
        public Nullable<int> parm_115 { get; set; }
        public Nullable<int> parm_116 { get; set; }
        public Nullable<int> parm_117 { get; set; }
        public Nullable<int> parm_118 { get; set; }
        public Nullable<int> parm_119 { get; set; }
        public Nullable<int> parm_120 { get; set; }
        public Nullable<int> parm_121 { get; set; }
        public Nullable<int> parm_122 { get; set; }
        public Nullable<int> parm_123 { get; set; }
        public Nullable<int> parm_124 { get; set; }
        public Nullable<int> parm_125 { get; set; }
        public Nullable<int> parm_126 { get; set; }
        public Nullable<int> parm_127 { get; set; }
        public Nullable<int> parm_128 { get; set; }
        public Nullable<int> FauCode1 { get; set; }
        public Nullable<int> FauCode2 { get; set; }
        public Nullable<int> FauCode3 { get; set; }
        public Nullable<int> FauCode4 { get; set; }
        public Nullable<int> FauCode5 { get; set; }
        public Nullable<int> FauCode6 { get; set; }
        public Nullable<int> FauCode7 { get; set; }
        public Nullable<int> FauCode8 { get; set; }
        public Nullable<int> FauCode9 { get; set; }
        public Nullable<int> FauCode10 { get; set; }
        public Nullable<int> FauCode11 { get; set; }
        public Nullable<int> FauCode12 { get; set; }
        public Nullable<int> FauCode13 { get; set; }
        public Nullable<int> FauCode14 { get; set; }
        public Nullable<int> FauCode15 { get; set; }
        public Nullable<int> FauCode16 { get; set; }
    }
}
