//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoronaDataCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_FUHE_LS_YX
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Parm_001 { get; set; }
        public string Parm_002 { get; set; }
        public Nullable<int> parm_004 { get; set; }
        public Nullable<System.DateTime> parm_006 { get; set; }
        public Nullable<int> FUHE_LS_Parm_048 { get; set; }
        public Nullable<int> FUHE_LS_Parm_049 { get; set; }
        public Nullable<int> FUHE_LS_Parm_050 { get; set; }
        public Nullable<int> FUHE_LS_Parm_051 { get; set; }
        public Nullable<int> FUHE_LS_Parm_052 { get; set; }
        public Nullable<int> FUHE_LS_Parm_053 { get; set; }
        public Nullable<int> FUHE_LS_Parm_054 { get; set; }
        public Nullable<int> FUHE_LS_Parm_055 { get; set; }
        public Nullable<int> FUHE_LS_Parm_056 { get; set; }
        public Nullable<int> FUHE_LS_Parm_057 { get; set; }
        public Nullable<int> FUHE_LS_Parm_058 { get; set; }
        public Nullable<int> FUHE_LS_Parm_059 { get; set; }
        public Nullable<int> FUHE_LS_Parm_060 { get; set; }
        public Nullable<int> FUHE_LS_Parm_061 { get; set; }
        public Nullable<int> FUHE_LS_Parm_062 { get; set; }
    
        public virtual Tb_Equipment_Status Tb_Equipment_Status { get; set; }
    }
}
